let MCQS = [
  {
    question:
      "Which of the following is not a data type supported by Javascript?",
    choice1: "Undefined",
    choice2: "Tuple",
    choice3: "Symbol",
    choice4: "Boolean",
    answer: 1,
  },
  {
    question: "Is Javascript a case sensitive language?",
    choice1: "Mixed",
    choice2: "False",
    choice3: "True",
    choice4: "does not have a case",
    answer: 2,
  },
  {
    question: "What are the scopes of a variable in JavaScript?",
    choice1: "Named variables, Global variables",
    choice2: "Global variables, Local variables",
    choice3: "Local variables, String variables",
    choice4: "Named variables, Global variables",
    answer: 1,
  },
  {
    question: "What is a Callback?",
    choice1: "A plain JavaScript function passed to some method as an argument",
    choice2: "Functions calling each-other",
    choice3: "Substance that returns the character of a specified index",
    choice4: "A call from the safaricom sim card",
    answer: 0,
  },
  {
    question:
      "Which of the following is not a way JavaScript code can be involved in a HTML file?",
    choice1: "External",
    choice2: "Exline",
    choice3: "Inline",
    choice4: "Internal",
    answer: 1,
  },
  {
    question: "Which symbol do we use to comment on a line?",
    choice1: "/* this is a comment*/",
    choice2: "||",
    choice3: "\\\\",
    choice4: "//",
    answer: 2,
  },
  {
    question: "Does JavaScript have an automatic type conversion?",
    choice1: "Sometimes maybe",
    choice2: "No",
    choice3: "I don't know",
    choice4: "Yes",
    answer: 3,
  },
  {
    question: "what is === operator?",
    choice1: "Variable assigner",
    choice2: "Equality operator",
    choice3: "Strict equality operator",
    choice4: "Assignment operator",
    answer: 2,
  },
  {
    question: "Which of the following symbol is used to comment a multiline?",
    choice1: "\\\\",
    choice4: "//",
    choice2: "||",
    choice3: "/**/",
    answer: 2,
  },
  {
    question:
      "Which of the following are not pop-up boxes available in javascript?",
    choice1: "Prompt",
    choice2: "Confirm",
    choice3: "Warn",
    choice4: "Alert",
    answer: 0,
  },
];
